import { NOTIFICATION_EXAMPLES } from '../../examples/pixel-notification';
import { DocComponentMeta } from '../types';

export const NOTIFICATION_META: DocComponentMeta = {
  id: 'pixel-notification',
  title: 'Notification',
  selector: 'pixel-notification-panel',
  category: 'feedback',
  status: 'experimental',
  summary:
    'Enterprise notification orchestration with desktop panel, banner, dialog, preferences, and pluggable sync adapters.',
  overview: [
    'PixelNotificationService is the application-facing orchestrator and exposes canonical, inbox, unread, archive, banner, and category-count signals from its internal store.',
    'The minimal-interruption default policy sends low/normal priority to the inbox and high/critical priority to both inbox and toast.',
    'Explicit channels override policy per record. Banner uses pixel-notification-banner; dialog escalations open through PixelDialogService.',
    'PixelToastService remains the toast renderer. The orchestrator adapts notification severity, state, progress, and actions to PixelToastConfig.',
    'Applications own WebSocket, SSE, polling, authentication, and reconnect lifecycles through PixelNotificationTransportAdapter, then call PixelNotificationSyncService.start().',
    'Persistence, analytics, and preferences are injectable. Quiet hours and muted categories suppress interruptive channels without rewriting stored channel policy.',
    'pixel-notification-item renders one controlled record; pixel-notification-panel adds filters and incremental rendering; groupNotifications() supports full-page recipes.',
    'Compose the panel inside pixel-popover and wrap the bell trigger with pixel-badge. Mobile drawer behavior is intentionally outside the current product scope.',
  ],
  useCases: [
    'Durable report, approval, account, billing, and security notifications',
    'High-priority events requiring both an inbox record and immediate toast',
    'Banner and critical-dialog escalations for operational and security workflows',
    'Deduplicated job lifecycle updates with progress',
    'Multi-tab / reconnect-safe sync through application-owned adapters',
    'An anchored desktop notification center with filters and incremental loading',
  ],
  themingNotes: [
    'Item tokens use the --pixel-notification-item-* namespace and derive from shared system tokens.',
    'Toast delivery uses the existing --pixel-toast-* and --pixel-sys-* contracts.',
    'Compact density reduces spacing while retaining effective action touch targets.',
    'Panel tokens use the --pixel-notification-panel-* namespace and remain viewport-clamped.',
    'Preferences and banner hosts inherit system surface/outline tokens.',
  ],
  accessibilityNotes: [
    'The item main action and every inline action use native button or link semantics.',
    'Unread, failed, completed, and archived states include text available to assistive technology; meaning never depends on color alone.',
    'Toast delivery inherits pixel-toast live-region, keyboard, and reduced-motion behavior.',
    'Dialog-channel records open as alertdialog; critical priority can disable dismiss.',
    'Use high/critical priority sparingly so assistive-technology users are not over-interrupted.',
    'The popover recipe restores trigger focus on Escape and dismisses on outside pointer or Tab-out.',
  ],
  imports: [
    'PixelNotificationService',
    'PixelNotificationSyncService',
    'PixelNotificationItemComponent',
    'PixelNotificationPanelComponent',
    'PixelNotificationBannerComponent',
    'PixelNotificationPreferencesComponent',
    'PixelPopoverComponent',
    'PixelPopoverTriggerDirective',
    'PixelBadgeComponent',
    'providePixelNotifications',
    'groupNotifications',
  ],
  inputs: [
    { name: 'notifications', type: 'readonly PixelNotification[]', defaultValue: '[]', description: 'Records available to the panel.' },
    { name: 'filter', type: "'all' | 'unread' | 'action-required'", defaultValue: "'all'", description: 'Two-way read/action filter.' },
    { name: 'category', type: 'string', defaultValue: "''", description: 'Two-way category filter.' },
    { name: 'pageSize', type: 'number', defaultValue: '20', description: 'Bounded incremental render size.' },
    { name: 'totalCount', type: 'number | null', defaultValue: 'null', description: 'Optional footer total when inbox is paged externally.' },
    { name: 'loading', type: 'boolean', defaultValue: 'false', description: 'Shows initial skeleton rows.' },
    { name: 'loadingMore', type: 'boolean', defaultValue: 'false', description: 'Shows incremental loading feedback.' },
    { name: 'hasMore', type: 'boolean', defaultValue: 'false', description: 'Signals an external page is available.' },
    { name: 'offline', type: 'boolean', defaultValue: 'false', description: 'Shows cached-data offline status.' },
    { name: 'errorMessage', type: 'string', defaultValue: "''", description: 'Shows recoverable load failure UI.' },
    { name: 'showViewAll', type: 'boolean', defaultValue: 'true', description: 'Shows the full-page navigation intent.' },
  ],
  outputs: [
    { name: 'notificationActivated', type: 'PixelNotificationItemActivateEvent', description: 'Main item activation intent.' },
    { name: 'actionClicked', type: 'PixelNotificationItemActionEvent', description: 'Inline action intent.' },
    { name: 'dismissClicked', type: 'PixelNotificationItemActivateEvent', description: 'Close/archive intent from the panel item dismiss control.' },
    { name: 'overflowClicked', type: 'PixelNotificationItemOverflowEvent', description: 'Overflow intent (full-page recipes; panel uses dismiss by default).' },
    { name: 'command', type: 'PixelNotificationPanelCommandEvent', description: 'Toolbar, pagination, retry, or view-all intent.' },
  ],
  serviceName: 'PixelNotificationService',
  serviceApi: [
    {
      name: 'publish',
      signature: '(draft: PixelNotificationCreate, options?) => string',
      description: 'Normalize, route, store, deduplicate, and deliver a notification.',
    },
    {
      name: 'setPreferences / preferences',
      signature: '(partial?) => void · Signal<Preferences>',
      description: 'Runtime preference muting, quiet hours, and channel disables.',
    },
    {
      name: 'hydrate',
      signature: '(records) => void',
      description: 'Replace canonical state without replaying delivery or outbound sync.',
    },
    {
      name: 'banners',
      signature: 'Signal<readonly PixelNotification[]>',
      description: 'Active banner-channel records after preference filtering.',
    },
    {
      name: 'markRead / archive / invokeAction / …',
      signature: 'see README API contract',
      description: 'Lifecycle and action orchestration with optional remote source flags.',
    },
  ],
  examples: NOTIFICATION_EXAMPLES,
};
