import { DocComponentMeta } from '../types';
import { DATA_GRID_EXAMPLES } from '../../examples/pixel-data-grid';

export const DOC_DATA_GRID_META: DocComponentMeta = {
  id: 'pixel-data-grid',
  title: 'Data grid',
  selector: 'pixel-data-grid',
  category: 'advanced',
  status: 'stable',
  summary:
    'Enterprise data grid: sorting, filtering, search, pagination, column resize/reorder/pin, selection, export, virtualization, grouping & aggregation, master-detail, and inline editing — client- or server-side, over a store-driven foundation.',
  overview: [
    'Import from pixel-ui/data-grid.',
    'pixel-data-grid is the library\'s enterprise table component, built phase by phase toward a full feature set.',
    'It uses a signal-backed store (like pixel-query-builder) so sorting, filtering, selection, virtualization, grouping, and editing layer onto one derivation pipeline.',
    'Phase 1 adds multi-column sort (shift-click), per-column filters, a global quick search, and pagination — client-side, server-side via criteriaChange, or fully managed via [dataSource].',
    'Phase 2 adds column power tooling: drag-resize, drag-reorder, pin/freeze left & right, a column chooser, per-column header menus, and persistable view state (getState/setState).',
    'Phase 3 adds selection (checkbox column, shift-range, select-all per page or across pages) and export to CSV / JSON / Excel / clipboard, including export-all that fetches every row from a DataSource.',
    'Phase 4 adds fixed-height row virtualization (only visible rows in the DOM) that composes with the sticky header and pinned columns, plus an infinite-scroll loadMore hook for incremental loading.',
    'Phase 5 adds row grouping (multi-level, collapsible, with counts), per-column aggregation (sum/avg/min/max/count/custom) in group headers and a grand-total footer, and master-detail expandable rows via the pixelGridDetail template.',
    'Phase 6 adds inline cell editing (built-in text/number/date/select/checkbox editors + pixelGridEditor custom templates, per-column validation, cellEdit event), ARIA grid roles, and keyboard navigation (arrow keys, Enter/F2 to edit, Esc to cancel).',
  ],
  useCases: [
    'Admin grids with sort, filter, search, and paging',
    'Server-driven tables backed by a DataSource (REST/GraphQL)',
    'Configurable grids whose column layout persists per user',
    'Wide grids needing frozen identity/action columns',
  ],
  themingNotes: [
    'Density compact / standard / comfortable adjusts cell padding, font size, and embedded control sizes (xs / sm / md).',
    'Sticky header pins within a scrollable body viewport; pinned columns freeze left/right without a body-edge divider.',
    'Consumes ambient --pixel-sys-* tokens, so it follows light / dark / prefers-color-scheme automatically; honors reduced-motion. The toolbar wraps on narrow viewports and the body scrolls horizontally.',
  ],
  accessibilityNotes: [
    'Renders role="grid" with aria-rowcount / aria-colcount, role="row" + aria-rowindex / aria-selected, and role="gridcell" / "columnheader" + aria-colindex; sortable headers expose aria-sort.',
    'Keyboard navigation: arrow keys + Home/End move a roving-tabindex cell focus; Enter/F2 edits a cell, Esc cancels.',
    'Column reorder uses native drag-and-drop; resize handles are pointer-driven. Loading and empty states expose status text.',
  ],
  imports: [
    'PixelDataGridComponent',
    'PixelDataGridCellDirective',
    'PixelDataGridDetailDirective',
    'PixelDataGridEditorDirective',
  ],
  inputs: [
    { name: 'data', type: 'readonly T[]', defaultValue: '[]', description: 'Row data (ignored when a dataSource is bound).' },
    { name: 'columns', type: 'PixelDataGridColumn<T>[]', defaultValue: '[]', description: 'Column definitions (sortable / filter per column).' },
    { name: 'rowId', type: '(row, index) => string | number', defaultValue: 'index', description: 'Stable row identity.' },
    { name: 'density', type: "'comfortable' | 'standard' | 'compact'", defaultValue: "'standard'", description: 'Row density.' },
    { name: 'searchable', type: 'boolean', defaultValue: 'false', description: 'Show a global quick-search box.' },
    { name: 'columnChooser', type: 'boolean', defaultValue: 'false', description: 'Toolbar menu to toggle column visibility.' },
    { name: 'resizableColumns', type: 'boolean', defaultValue: 'false', description: 'Drag-resize handles (per-column resizable opts out).' },
    { name: 'reorderableColumns', type: 'boolean', defaultValue: 'false', description: 'Drag column headers to reorder.' },
    { name: 'pinnableColumns', type: 'boolean', defaultValue: 'false', description: 'Pin left/right via the header menu.' },
    { name: 'selectionMode', type: "'none' | 'single' | 'multiple'", defaultValue: "'none'", description: 'Row selection mode (multiple adds a checkbox column).' },
    { name: 'selectedRows', type: 'T[]', defaultValue: '[]', description: 'Two-way selected rows (by rowId).' },
    { name: 'exportable', type: 'boolean', defaultValue: 'false', description: 'Toolbar export menu (CSV/JSON/Excel/clipboard).' },
    { name: 'exportFileName', type: 'string', defaultValue: "'grid-export'", description: 'Base download file name.' },
    { name: 'exportFormats', type: 'PixelDataGridExportFormat[]', defaultValue: "['csv','json','excel','clipboard']", description: 'Formats offered in the export menu.' },
    { name: 'multiSort', type: 'boolean', defaultValue: 'true', description: 'Allow shift-click multi-column sort.' },
    { name: 'sortModel', type: 'PixelDataGridSortDescriptor[]', defaultValue: '[]', description: 'Two-way multi-column sort model.' },
    { name: 'filters', type: 'PixelDataGridFilterState', defaultValue: '{}', description: 'Two-way per-column filter state.' },
    { name: 'quickFilter', type: 'string', defaultValue: "''", description: 'Two-way global search text.' },
    { name: 'paginated', type: 'boolean', defaultValue: 'false', description: 'Enable the pagination footer.' },
    { name: 'pageSize', type: 'number', defaultValue: '10', description: 'Two-way page size.' },
    { name: 'serverSide', type: 'boolean', defaultValue: 'false', description: 'Render data verbatim and emit criteriaChange.' },
    { name: 'totalRecords', type: 'number | null', defaultValue: 'null', description: 'Total count for server-side paging.' },
    { name: 'dataSource', type: 'PixelDataGridDataSource<T> | null', defaultValue: 'null', description: 'Pluggable source; fetches on criteria change.' },
    { name: 'virtualScroll', type: 'boolean', defaultValue: 'false', description: 'Fixed-height row windowing (bypasses pagination).' },
    { name: 'rowHeight', type: 'number', defaultValue: '0', description: 'Virtual row height in px (0 = derive from density).' },
    { name: 'virtualHeight', type: 'number', defaultValue: '480', description: 'Virtual viewport height in px.' },
    { name: 'infiniteScroll', type: 'boolean', defaultValue: 'false', description: 'Emit loadMore near the bottom.' },
    { name: 'hasMore', type: 'boolean', defaultValue: 'true', description: 'Whether more rows can load (gates loadMore).' },
    { name: 'groupBy', type: 'string[]', defaultValue: '[]', description: 'Fields to group rows by (collapsible, aggregated).' },
    { name: 'expandableRows', type: 'boolean', defaultValue: 'false', description: 'Master-detail toggle + pixelGridDetail template.' },
    { name: 'editable', type: 'boolean', defaultValue: 'false', description: 'Master switch for inline cell editing (per-column editable opts in).' },
    { name: 'loading', type: 'boolean', defaultValue: 'false', description: 'Busy flag (also set during DataSource fetch).' },
    { name: 'loadingMode', type: "'loader' | 'skeleton'", defaultValue: "'skeleton'", description: 'Spinner overlay vs in-body skeleton rows while loading.' },
    { name: 'showSkeleton', type: 'boolean', defaultValue: 'false', description: 'Force in-body skeleton rows (headers/columns stay).' },
    { name: 'skeletonRows', type: 'number', defaultValue: '0', description: '0 = auto (pageSize / viewport / known rows / 10). Positive = fixed count.' },
    { name: 'emptyMessage', type: 'string', defaultValue: "'No records to display.'", description: 'Empty-state text.' },
  ],
  outputs: [
    { name: 'rowClick', type: 'PixelDataGridRowClickEvent<T>', description: 'Row activated while clickableRows is on.' },
    { name: 'sortChange', type: 'PixelDataGridSortEvent', description: 'Sort model changed.' },
    { name: 'pageChange', type: 'PixelDataGridPageEvent', description: 'Page index or size changed.' },
    { name: 'criteriaChange', type: 'PixelDataGridCriteria', description: 'Sort, filter, search, or page changed.' },
    { name: 'columnVisibilityChange', type: 'string[]', description: 'Visible column fields changed.' },
    { name: 'stateChange', type: 'PixelDataGridState', description: 'Column layout (order/width/visibility/pin) changed.' },
    { name: 'selectionChange', type: 'T[]', description: 'Selected rows changed.' },
    { name: 'loadMore', type: 'void', description: 'User scrolled near the bottom (infiniteScroll + hasMore).' },
    { name: 'cellEdit', type: 'PixelDataGridCellEditEvent<T>', description: 'An inline cell edit was committed.' },
  ],
  composeWith: [
    'pixel-empty-state',
    'pixel-button',
    'pixel-input',
    'pixel-export',
    'pixel-loader',
    'pixel-paginator',
  ],
  supports: ['keyboard', 'theming', 'dark-mode', 'async', 'skeleton', 'forms'],
  examples: DATA_GRID_EXAMPLES,
};
