import { TOAST_EXAMPLES } from '../../examples/pixel-toast';
import { DocComponentMeta } from '../types';

export const TOAST_META: DocComponentMeta = {
  id: 'pixel-toast',
  title: 'Toast',
  selector: 'pixel-toast',
  category: 'feedback',
  status: 'stable',
  summary:
    'Global and inline toast notifications with PixelToastService, three visual variants, queue management, promise lifecycle, and accessible live regions.',
  overview: [
    'Add pixel-toast-container once in your app shell, then inject PixelToastService (providedIn root) from any component.',
    'Three variants — soft, solid, and outlined — plus semantic types (success, error, warning, info, loading, offline, online, system, custom).',
    'Overlay toasts anchor to six positions; inline toasts render in document flow via pixel-toast-inline and toast.inline().',
    'Use toast.configure() for global defaults, toast.update() to patch active toasts, and toast.promise() for async lifecycles.',
  ],
  useCases: [
    'Success and error feedback after async actions',
    'Promise-driven loading → success/error transitions',
    'Persistent system notices with undo/retry actions',
    'In-page form banners with inline placement and outlined variant',
    'Connectivity offline/online state messaging',
  ],
  themingNotes: [
    'Soft variant uses --pixel-sys-{type}-container tokens aligned with semantic color banners.',
    'Outlined variant suits inline banners with a semantic border and tinted surface.',
    'Solid variant uses filled semantic surfaces for high-emphasis overlay toasts.',
    'Configure global defaults with toast.configure({ position, maxVisible, variant, timeOut }).',
  ],
  accessibilityNotes: [
    'Error toasts use role="alert"; other types use polite live regions.',
    'Supports keyboard focus on action buttons and close controls.',
    'Respects prefers-reduced-motion for enter/exit animations.',
    'Swipe-to-dismiss and Escape-to-dismiss when a toast has focus.',
    'Always provide ariaLabel when title is omitted for icon-only or compact toasts.',
  ],
  imports: [
    'PixelToastService',
    'PixelToastContainerComponent',
    'PixelToastInlineComponent',
    'PixelToastComponent',
  ],
  serviceName: 'PixelToastService',
  serviceApi: [
    { name: 'configure', signature: '(config: Partial<PixelToastGlobalConfig>) => void', description: 'Set global defaults for position, variant, queue, timeout, and interaction.' },
    { name: 'show', signature: '(config?: PixelToastConfig) => string', description: 'Show a toast with full config; returns toast id.' },
    { name: 'success', signature: '(title, message?, config?) => string', description: 'Semantic success toast shortcut.' },
    { name: 'error', signature: '(title, message?, config?) => string', description: 'Semantic error toast with role alert.' },
    { name: 'warning', signature: '(title, message?, config?) => string', description: 'Semantic warning toast shortcut.' },
    { name: 'info', signature: '(title, message?, config?) => string', description: 'Semantic info toast shortcut.' },
    { name: 'loading', signature: '(title, message?, config?) => string', description: 'Non-dismissible loading toast until removed or updated.' },
    { name: 'offline', signature: '(title, message?, config?) => string', description: 'Persistent offline connectivity toast.' },
    { name: 'online', signature: '(title, message?, config?) => string', description: 'Online/restored connectivity toast.' },
    { name: 'system', signature: '(title, message?, config?) => string', description: 'System/maintenance notice toast.' },
    { name: 'custom', signature: '(title, message?, config?) => string', description: 'Custom type with optional icon and metadata.' },
    { name: 'inline', signature: '(config: PixelToastConfig) => string', description: 'Push an inline toast into pixel-toast-inline anchor.' },
    { name: 'promise', signature: '(task, messages, config?) => Promise<T>', description: 'Loading → success/error lifecycle around a Promise.' },
    { name: 'update', signature: '(id, patch) => void', description: 'Patch an active toast (e.g. loading → success).' },
    { name: 'setProgress', signature: '(id, percent) => void', description: 'Update determinate progress on a toast.' },
    { name: 'setExpanded', signature: '(id, expanded) => void', description: 'Toggle expandable details section.' },
    { name: 'remove', signature: '(id, reason?) => void', description: 'Dismiss a toast by id.' },
    { name: 'clear', signature: '(position?) => void', description: 'Clear overlay toasts, optionally by position.' },
    { name: 'clearInline', signature: '(anchor?) => void', description: 'Clear inline toasts for an anchor.' },
  ],
  inputs: [
    { name: 'type', type: 'PixelToastType', defaultValue: "'default'", description: 'Semantic toast type (success, error, warning, info, loading, …).' },
    { name: 'variant', type: "'soft' | 'solid' | 'outlined'", defaultValue: "'soft'", description: 'Visual variant — soft tinted, solid filled, or outlined border.' },
    { name: 'placement', type: "'overlay' | 'inline'", defaultValue: "'overlay'", description: 'Fixed overlay stack or in-page inline flow.' },
    { name: 'position', type: 'PixelToastPosition', defaultValue: "'top-right'", description: 'Overlay anchor (top/bottom × left/center/right).' },
    { name: 'title', type: 'string', description: 'Primary toast heading.' },
    { name: 'message', type: 'string', description: 'Supporting body copy.' },
    { name: 'details', type: 'string', description: 'Expandable supplementary details.' },
    { name: 'size', type: "'xs' | 'sm' | 'md' | 'lg'", defaultValue: "'md'", description: 'Density scale.' },
    { name: 'timeOut', type: 'number', defaultValue: '5000', description: 'Auto-dismiss delay in ms.' },
    { name: 'disableTimeOut', type: 'boolean', defaultValue: 'false', description: 'Keep the toast until manually dismissed.' },
    { name: 'closeButton', type: 'boolean', defaultValue: 'true', description: 'Show a dismiss control.' },
    { name: 'progressBar', type: 'boolean', defaultValue: 'true', description: 'Show auto-dismiss progress bar.' },
    { name: 'actions', type: 'readonly PixelToastAction[]', description: 'Primary/secondary action buttons.' },
    { name: 'undoAction', type: 'PixelToastAction', description: 'Undo button with onUndo callback.' },
    { name: 'retryAction', type: 'PixelToastAction', description: 'Retry button with onRetry callback.' },
    { name: 'contentMaxHeight', type: 'string', description: 'Max scroll height for long title/message (e.g. 12rem).' },
    { name: 'expandable', type: 'boolean', defaultValue: 'false', description: 'Collapsible details section.' },
    { name: 'imageSrc', type: 'string', description: 'Avatar image for custom/team notifications.' },
    { name: 'icon', type: 'string', description: 'Material icon override for custom type.' },
    { name: 'ariaLabel', type: 'string', description: 'Accessible name when title is omitted.' },
  ],
  outputs: [
    { name: 'dismiss', type: 'PixelToastDismissEvent', description: 'Fires when a toast is dismissed.' },
    { name: 'action', type: 'PixelToastActionEvent', description: 'Fires when an action button is clicked.' },
  ],
  examples: TOAST_EXAMPLES,
};
