import { DocComponentMeta } from '../types';
import { EDITOR_EXAMPLES } from '../../examples/pixel-editor';

export const EDITOR_META: DocComponentMeta = {
  id: 'pixel-editor',
  title: 'Editor',
  selector: 'pixel-editor',
  category: 'form-controls',
  status: 'beta',
  summary:
    'Jira-like rich text editor with TipTap document engine, pixel-composed toolbar, and status bar.',
  overview: [
    'Canonical value is structured JSON (PixelEditorDoc). HTML is emitted via htmlChange; ADF is out of v1.',
    'TipTap packages are optional peerDependencies — install them when you use PixelEditorComponent.',
    'Toolbar reuses pixel-button, pixel-divider, pixel-menu, pixel-popover, and pixel-tooltip.',
    'Supports info/note/success/warning/error callout panels and interactive task lists (inline checkbox + text).',
    'Images: align, width, float, captions, drag-resize, canvas crop; contextual image toolbar.',
    'Slash `/` command palette; find & replace (Ctrl/Cmd+F); table row/col chrome; font sizes; clear formatting.',
    'Copy HTML / Markdown from the status bar; countMode cycles words / characters.',
    'Mentions (@), curated emoji (~100), date chips (local YYYY-MM-DD), special characters.',
    'toolbarPosition top|bottom; bottom placement hides the status bar.',
    'Integrates with Angular forms via ControlValueAccessor + Validator.',
  ],
  useCases: [
    'Issue and ticket description fields',
    'Comment and documentation bodies with headings, lists, and callouts',
    'Forms that need rich text with optional fullscreen editing',
  ],
  themingNotes: [
    'Override --pixel-editor-* tokens on the host for border, radius, surface, and focus ring.',
    'Text color, highlight, and link marks use --pixel-editor-ink-* / --pixel-editor-mark-* / --pixel-editor-link so they stay readable in light and dark themes.',
    'Toolbar and status bar inherit system tokens; dark scheme follows [data-theme] / data-color-scheme.',
  ],
  accessibilityNotes: [
    'Toolbar uses role="toolbar" with aria-label on every icon control; picker glyphs are ≥44×44px with pixelTooltip.',
    'Surface exposes role="textbox" and aria-multiline (TipTap owns caret).',
    'Status bar is role="status" with aria-live="polite"; find bar announces match counts.',
    'loading sets aria-busy; Escape exits fullscreen / closes find; prefers-reduced-motion honored.',
  ],
  imports: ['PixelEditorComponent'],
  inputs: [
    { name: 'label', type: 'string', defaultValue: "''", description: 'Visible label above the editor.' },
    { name: 'placeholder', type: 'string', defaultValue: "''", description: 'Empty-canvas placeholder.' },
    { name: 'value', type: 'PixelEditorDoc | null', defaultValue: 'null', description: 'Canonical JSON document.' },
    { name: 'toolbar', type: 'PixelEditorToolbarConfig', defaultValue: '{}', description: 'Show/hide toolbar groups.' },
    { name: 'toolbarPosition', type: "'top' | 'bottom'", defaultValue: "'top'", description: 'Places the toolbar above or below the canvas. Bottom hides the status bar.' },
    { name: 'countMode', type: "'words' | 'characters' | 'charactersWithSpaces'", defaultValue: "'words'", description: 'Status-bar count mode (click label to cycle).' },
    { name: 'mentionItems', type: 'readonly PixelEditorMentionItem[]', defaultValue: '[]', description: 'People/entities for @mentions.' },
    { name: 'size', type: "'sm' | 'md' | 'lg'", defaultValue: "'md'", description: 'Chrome density.' },
    { name: 'minHeight', type: 'string', defaultValue: "'12rem'", description: 'Minimum editing surface height.' },
    { name: 'disabled', type: 'boolean', defaultValue: 'false', description: 'Disables interaction.' },
    { name: 'readonly', type: 'boolean', defaultValue: 'false', description: 'Read-only surface.' },
    { name: 'showToolbar', type: 'boolean', defaultValue: 'true', description: 'Renders the formatting toolbar.' },
    { name: 'showStatusBar', type: 'boolean', defaultValue: 'true', description: 'Renders the footer status bar (ignored when toolbarPosition is bottom).' },
    { name: 'fullscreen', type: 'boolean', defaultValue: 'false', description: 'Fullscreen host (two-way model).' },
    { name: 'saveState', type: "PixelEditorSaveState", defaultValue: "'idle'", description: 'Status-bar save indicator.' },
    { name: 'savedAtLabel', type: 'string', defaultValue: "''", description: 'Relative time next to save state.' },
    { name: 'blockKind', type: 'PixelEditorBlockKind | null', defaultValue: 'null', description: 'Optional override for status-bar block breadcrumb; otherwise follows selection.' },
    { name: 'showSkeleton', type: 'boolean', defaultValue: 'false', description: 'Replaces chrome with pixel-skeleton.' },
    { name: 'loading', type: 'boolean', defaultValue: 'false', description: 'Surface loading overlay + aria-busy.' },
    { name: 'loadingLabel', type: 'string', defaultValue: "'Loading'", description: 'Accessible label for the loading overlay.' },
    { name: 'required', type: 'boolean', defaultValue: 'false', description: 'Invalid when the document has no plain text.' },
    { name: 'minLength', type: 'number', defaultValue: '0', description: 'Minimum trimmed plain-text length (0 disables).' },
    { name: 'emptyHeading', type: 'string', defaultValue: "''", description: 'Optional empty-state heading when the doc has no text.' },
    { name: 'emptyDescription', type: 'string', defaultValue: "''", description: 'Optional empty-state description.' },
  ],
  outputs: [
    { name: 'valueChange', type: 'PixelEditorDoc', description: 'Emits when the JSON document changes.' },
    { name: 'htmlChange', type: 'string', description: 'Emits derived HTML.' },
    { name: 'mentionQuery', type: 'PixelEditorMentionQuery', description: 'Emits when the user types in @ mention search.' },
    { name: 'imageRequest', type: 'PixelEditorImageRequest', description: 'Emits on image upload/URL insert or canvas crop (source: upload | url | crop).' },
  ],
  examples: EDITOR_EXAMPLES,
};
