import { DocComponentMeta } from '../types';
import { AUTOCOMPLETE_EXAMPLES } from '../../examples/pixel-autocomplete';

export const AUTOCOMPLETE_META: DocComponentMeta = {
  id: 'pixel-autocomplete',
  title: 'Autocomplete',
  selector: 'pixel-autocomplete',
  category: 'form-controls',
  status: 'stable',
  summary:
    'Text field with a typeahead suggestion panel, client-side filtering or server search, and WAI-ARIA combobox semantics.',
  overview: [
    'Combines a text input with a body-appended overlay panel for filtered suggestions.',
    'Supports flat or grouped options with rich layouts: avatars, icons, subtitles, and meta text.',
    'Integrates with Angular reactive and template-driven forms via ControlValueAccessor and Validator.',
    'Implements full keyboard navigation (arrows, Enter, Escape) with search-match highlighting.',
    'Server-search mode debounces the searchChange event so the parent drives filtering.',
  ],
  useCases: [
    'Location and address pickers with real-time suggestions',
    'User or team selectors with avatar thumbnails and async queries',
    'Tag or label pickers that accept both list options and free text',
    'Search bars with intelligent typeahead and grouped result categories',
  ],
  themingNotes: [
    'Panel colors, radii, and spacing are controlled via --pixel-autocomplete-* CSS custom properties.',
    'Option hover and selected states use color-mix() for theme-aware highlights.',
    'Inherits pixel-input field tokens for border, focus ring, and label styles.',
    'Dark mode is supported via prefers-color-scheme: dark and [data-theme="enterprise-dark"].',
  ],
  accessibilityNotes: [
    'WAI-ARIA combobox pattern: role="combobox" on the input, role="listbox" on the panel, role="option" on each item.',
    'aria-expanded, aria-controls, and aria-activedescendant are kept in sync while the panel is open.',
    'aria-selected, aria-disabled, and aria-required reflect option and control states.',
    'Keyboard: Arrow keys navigate, Enter selects, Escape closes, Tab commits and moves focus.',
    'Screen-reader label and helper text are wired via aria-label / aria-describedby fallbacks.',
  ],
  imports: ['PixelAutocompleteComponent'],
  inputs: [
    { name: 'value', type: 'unknown | null', defaultValue: 'null', description: 'Controlled value; matches an option value or free text when allowCustomValue=true.' },
    { name: 'options', type: 'readonly PixelAutocompleteOption[]', defaultValue: '[]', description: 'Flat suggestions list rendered in the panel.' },
    { name: 'groups', type: 'readonly PixelAutocompleteGroup[]', defaultValue: '[]', description: 'Pre-grouped suggestions; preferred when grouped=true.' },
    { name: 'label', type: 'string', defaultValue: "''", description: 'Visible field label text.' },
    { name: 'placeholder', type: 'string', defaultValue: "''", description: 'Placeholder shown when the field is empty.' },
    { name: 'size', type: "'xs' | 'sm' | 'md' | 'lg'", defaultValue: "'md'", description: 'Density and typography scale.' },
    { name: 'labelPosition', type: "'top' | 'left' | 'floating' | 'hidden'", defaultValue: "'top'", description: 'Label layout relative to the field.' },
    { name: 'disabled', type: 'boolean', defaultValue: 'false', description: 'Prevents all interaction and applies disabled styling.' },
    { name: 'readonly', type: 'boolean', defaultValue: 'false', description: 'Blocks edits but allows focus and keyboard navigation.' },
    { name: 'required', type: 'boolean', defaultValue: 'false', description: 'Marks the control required for validation and shows a required indicator.' },
    { name: 'helperText', type: 'string', defaultValue: "''", description: 'Hint copy rendered beneath the field.' },
    { name: 'validationMessages', type: 'PixelAutocompleteValidationMessages', defaultValue: '{}', description: 'Map of Angular error codes to user-facing messages shown when touched/dirty.' },
    { name: 'clearable', type: 'boolean', defaultValue: 'true', description: 'Shows a clear button when the field has text.' },
    { name: 'loading', type: 'boolean', defaultValue: 'false', description: 'Displays a loading indicator while async suggestions are being fetched.' },
    { name: 'showSkeleton', type: 'boolean', defaultValue: 'false', description: 'Renders a skeleton placeholder while initial data loads.' },
    { name: 'allowCustomValue', type: 'boolean', defaultValue: 'true', description: 'When true, free typed text becomes the value if it matches no option; when false, unmatched input is discarded on blur.' },
    { name: 'serverSearch', type: 'boolean', defaultValue: 'false', description: 'Skips local filtering; the parent supplies filtered options in response to searchChange.' },
    { name: 'searchDebounceMs', type: 'number', defaultValue: '300', description: 'Debounce delay in milliseconds before searchChange is emitted.' },
    { name: 'minChars', type: 'number', defaultValue: '0', description: 'Minimum characters typed before the panel opens or a search emits.' },
    { name: 'openOnFocus', type: 'boolean', defaultValue: 'true', description: 'Opens the panel when the field gains focus (if suggestions are available).' },
    { name: 'grouped', type: 'boolean', defaultValue: 'false', description: 'Enables grouped rendering via the option.group key or the groups input.' },
    { name: 'highlightSearchMatches', type: 'boolean', defaultValue: 'true', description: 'Highlights matched query substrings inside option labels.' },
    { name: 'visibleOptionCount', type: 'number', defaultValue: '6', description: 'Maximum option rows visible before the panel scrolls.' },
    { name: 'openDirection', type: "'auto' | 'top' | 'bottom'", defaultValue: "'auto'", description: 'Preferred direction for panel placement relative to the trigger.' },
    { name: 'scrollBehavior', type: "'close' | 'reposition' | 'block'", defaultValue: "'reposition'", description: 'Behaviour when the page scrolls while the panel is open.' },
    { name: 'panelWidth', type: "'auto' | 'match-trigger' | 'custom'", defaultValue: "'match-trigger'", description: 'Panel width strategy.' },
    { name: 'panelCustomWidth', type: 'string', defaultValue: "'20rem'", description: 'CSS width applied when panelWidth=custom.' },
    { name: 'emptyStateMessage', type: 'string', defaultValue: "'No suggestions.'", description: 'Message shown when no options are provided.' },
    { name: 'noResultMessage', type: 'string', defaultValue: "'No matching results.'", description: 'Message shown when the query matches no option.' },
    { name: 'displayWith', type: '(option: PixelAutocompleteOption) => string', defaultValue: 'option.label', description: 'Custom formatter for the field text once an option is selected.' },
    { name: 'compareWith', type: '(a: unknown, b: unknown) => boolean', defaultValue: 'Object.is', description: 'Equality function used when matching values against options (useful for object values).' },
    { name: 'ariaLabel', type: 'string', defaultValue: "''", description: 'Accessible name override when no visible label is present.' },
    { name: 'ariaDescribedBy', type: 'string', defaultValue: "''", description: 'Additional element ids merged into aria-describedby.' },
  ],
  outputs: [
    { name: 'valueChange', type: 'unknown', description: 'Emits the committed value whenever a selection is made or free text is committed.' },
    { name: 'optionSelected', type: 'PixelAutocompleteSelectionChange', description: 'Rich selection payload including the option object and interaction source (mouse or keyboard).' },
    { name: 'inputChange', type: 'string', description: 'Mirrors the native input event with the current text on every keystroke.' },
    { name: 'searchChange', type: 'string', description: 'Debounced search query emitted only when serverSearch=true.' },
    { name: 'openChange', type: 'boolean', description: 'Emits true when the panel opens and false when it closes.' },
    { name: 'focusChange', type: 'boolean', description: 'Emits true when the field receives focus.' },
    { name: 'clearClick', type: 'void', description: 'Fires when the clear button is clicked.' },
    { name: 'enterPress', type: 'KeyboardEvent', description: 'Fires when the Enter key is pressed inside the field.' },
  ],
  examples: AUTOCOMPLETE_EXAMPLES,
};
