/** Curated emoji set for the editor picker (no emoji-mart). */
export const PIXEL_EDITOR_EMOJI: readonly { readonly glyph: string; readonly label: string }[] = [
  // Faces
  { glyph: '😀', label: 'Grinning' },
  { glyph: '😁', label: 'Beaming' },
  { glyph: '😂', label: 'Joy' },
  { glyph: '🤣', label: 'ROFL' },
  { glyph: '😊', label: 'Smile' },
  { glyph: '😇', label: 'Halo' },
  { glyph: '🙂', label: 'Slight smile' },
  { glyph: '😉', label: 'Wink' },
  { glyph: '😍', label: 'Heart eyes' },
  { glyph: '🥰', label: 'Smiling hearts' },
  { glyph: '😘', label: 'Kiss' },
  { glyph: '🤗', label: 'Hug' },
  { glyph: '🤔', label: 'Thinking' },
  { glyph: '🤨', label: 'Raised eyebrow' },
  { glyph: '😐', label: 'Neutral' },
  { glyph: '😏', label: 'Smirk' },
  { glyph: '😒', label: 'Unamused' },
  { glyph: '🙄', label: 'Eye roll' },
  { glyph: '😬', label: 'Grimace' },
  { glyph: '😌', label: 'Relieved' },
  { glyph: '😔', label: 'Pensive' },
  { glyph: '😴', label: 'Sleeping' },
  { glyph: '😷', label: 'Mask' },
  { glyph: '🤒', label: 'Sick' },
  { glyph: '😎', label: 'Cool' },
  { glyph: '🤓', label: 'Nerd' },
  { glyph: '🧐', label: 'Monocle' },
  { glyph: '😕', label: 'Confused' },
  { glyph: '😟', label: 'Worried' },
  { glyph: '😮', label: 'Open mouth' },
  { glyph: '😲', label: 'Astonished' },
  { glyph: '😳', label: 'Flushed' },
  { glyph: '🥺', label: 'Pleading' },
  { glyph: '😢', label: 'Cry' },
  { glyph: '😭', label: 'Sob' },
  { glyph: '😱', label: 'Scream' },
  { glyph: '😤', label: 'Triumph' },
  { glyph: '😡', label: 'Angry' },
  { glyph: '🤯', label: 'Exploding head' },
  { glyph: '🥳', label: 'Party face' },
  { glyph: '🤠', label: 'Cowboy' },
  { glyph: '👻', label: 'Ghost' },
  { glyph: '🤖', label: 'Robot' },
  // Gestures
  { glyph: '👋', label: 'Wave' },
  { glyph: '👌', label: 'OK hand' },
  { glyph: '✌️', label: 'Victory' },
  { glyph: '🤞', label: 'Crossed fingers' },
  { glyph: '🤟', label: 'Love you' },
  { glyph: '🤘', label: 'Rock on' },
  { glyph: '🤙', label: 'Call me' },
  { glyph: '👍', label: 'Thumbs up' },
  { glyph: '👎', label: 'Thumbs down' },
  { glyph: '👏', label: 'Clap' },
  { glyph: '🙌', label: 'Raising hands' },
  { glyph: '👐', label: 'Open hands' },
  { glyph: '🤝', label: 'Handshake' },
  { glyph: '🙏', label: 'Folded hands' },
  { glyph: '💪', label: 'Muscle' },
  { glyph: '👀', label: 'Eyes' },
  { glyph: '🧠', label: 'Brain' },
  // Hearts / status
  { glyph: '❤️', label: 'Red heart' },
  { glyph: '🧡', label: 'Orange heart' },
  { glyph: '💛', label: 'Yellow heart' },
  { glyph: '💚', label: 'Green heart' },
  { glyph: '💙', label: 'Blue heart' },
  { glyph: '💜', label: 'Purple heart' },
  { glyph: '🖤', label: 'Black heart' },
  { glyph: '💔', label: 'Broken heart' },
  { glyph: '💯', label: 'Hundred' },
  { glyph: '✅', label: 'Check' },
  { glyph: '❌', label: 'Cross' },
  { glyph: '⚠️', label: 'Warning' },
  { glyph: '🚫', label: 'Prohibited' },
  { glyph: '💡', label: 'Idea' },
  { glyph: '💬', label: 'Speech' },
  { glyph: '🔔', label: 'Bell' },
  // Objects / work
  { glyph: '🔥', label: 'Fire' },
  { glyph: '✨', label: 'Sparkles' },
  { glyph: '⭐', label: 'Star' },
  { glyph: '🎉', label: 'Party' },
  { glyph: '🎊', label: 'Confetti' },
  { glyph: '🎈', label: 'Balloon' },
  { glyph: '🎁', label: 'Gift' },
  { glyph: '📌', label: 'Pin' },
  { glyph: '📍', label: 'Round pin' },
  { glyph: '🔗', label: 'Link' },
  { glyph: '📎', label: 'Paperclip' },
  { glyph: '📝', label: 'Memo' },
  { glyph: '📋', label: 'Clipboard' },
  { glyph: '📁', label: 'Folder' },
  { glyph: '📂', label: 'Open folder' },
  { glyph: '📅', label: 'Calendar' },
  { glyph: '⏰', label: 'Alarm' },
  { glyph: '⏳', label: 'Hourglass' },
  { glyph: '🚀', label: 'Rocket' },
  { glyph: '💻', label: 'Laptop' },
  { glyph: '🖥️', label: 'Desktop' },
  { glyph: '📱', label: 'Phone' },
  { glyph: '📧', label: 'Email' },
  { glyph: '🔑', label: 'Key' },
  { glyph: '🔒', label: 'Locked' },
  { glyph: '🔓', label: 'Unlocked' },
  { glyph: '🛠️', label: 'Tools' },
  { glyph: '⚙️', label: 'Gear' },
  { glyph: '🐛', label: 'Bug' },
  { glyph: '🎯', label: 'Target' },
  { glyph: '🏆', label: 'Trophy' },
  { glyph: '☕', label: 'Coffee' },
  { glyph: '🍕', label: 'Pizza' },
];

/** Common special characters / symbols. */
export const PIXEL_EDITOR_SPECIAL_CHARS: readonly { readonly glyph: string; readonly label: string }[] = [
  { glyph: '—', label: 'Em dash' },
  { glyph: '–', label: 'En dash' },
  { glyph: '…', label: 'Ellipsis' },
  { glyph: '•', label: 'Bullet' },
  { glyph: '·', label: 'Middle dot' },
  { glyph: '©', label: 'Copyright' },
  { glyph: '®', label: 'Registered' },
  { glyph: '™', label: 'Trademark' },
  { glyph: '°', label: 'Degree' },
  { glyph: '±', label: 'Plus-minus' },
  { glyph: '×', label: 'Multiply' },
  { glyph: '÷', label: 'Divide' },
  { glyph: '≠', label: 'Not equal' },
  { glyph: '≤', label: 'Less or equal' },
  { glyph: '≥', label: 'Greater or equal' },
  { glyph: '→', label: 'Arrow right' },
  { glyph: '←', label: 'Arrow left' },
  { glyph: '↔', label: 'Arrow both' },
  { glyph: '€', label: 'Euro' },
  { glyph: '£', label: 'Pound' },
  { glyph: '¥', label: 'Yen' },
  { glyph: '§', label: 'Section' },
  { glyph: '¶', label: 'Pilcrow' },
  { glyph: '★', label: 'Star' },
];

export type PixelEditorMentionItem = {
  readonly id: string;
  readonly label: string;
  readonly subtitle?: string;
};

export type PixelEditorMentionQuery = {
  readonly query: string;
};
