/**
 * Locale-aware relative timestamps for feeds and notification lists.
 * Built on `Intl.RelativeTimeFormat` — no third-party date library.
 */

export type PixelRelativeTimeStyle = 'long' | 'short' | 'narrow' | 'compact';
export type PixelRelativeTimeNumeric = 'always' | 'auto';

/**
 * Labels for the `compact` style. Override to localise ultra-dense relative phrases
 * (e.g. `"3m ago"`, `"2h ago"`) which cannot be generated by `Intl.RelativeTimeFormat`.
 *
 * Every field has a format string with a single `{n}` placeholder that is replaced by the
 * numeric value. Set `nowLabel` to a bare word like `"jetzt"` (no placeholder needed).
 */
export interface PixelRelativeTimeCompactLabels {
  /** Label for < 1 min ago/ahead; no `{n}` placeholder. @default 'now' */
  readonly nowLabel?: string;
  /** Template for minutes in the past, e.g. `'{n}m ago'`. @default '{n}m ago' */
  readonly minutesAgo?: string;
  /** Template for minutes in the future, e.g. `'in {n}m'`. @default 'in {n}m' */
  readonly minutesIn?: string;
  /** Template for hours in the past. @default '{n}h ago' */
  readonly hoursAgo?: string;
  /** Template for hours in the future. @default 'in {n}h' */
  readonly hoursIn?: string;
  /** Template for days in the past. @default '{n}d ago' */
  readonly daysAgo?: string;
  /** Template for days in the future. @default 'in {n}d' */
  readonly daysIn?: string;
}

export interface PixelRelativeTimeOptions {
  /** BCP 47 locale; defaults to the runtime locale. */
  readonly locale?: string;
  /** Reference "now" for tests and clock skew control. */
  readonly now?: number | Date;
  /**
   * `auto` yields natural forms like "yesterday" / "now"; `always` keeps numeric phrases.
   * @default 'auto'
   */
  readonly numeric?: PixelRelativeTimeNumeric;
  /**
   * Relative phrase length. `compact` uses ultra-dense forms like `3m ago` / `2h ago`
   * (notification panels); other values use `Intl.RelativeTimeFormat`.
   * @default 'long'
   */
  readonly style?: PixelRelativeTimeStyle;
  /**
   * Switch to an absolute local date/time after this many calendar days.
   * Pass `null` to keep relative units through years.
   * @default 7
   */
  readonly absoluteAfterDays?: number | null;
  /**
   * IANA timezone identifier (e.g. `'Asia/Kolkata'`) used when falling back to an absolute
   * timestamp. Defaults to the viewer's browser timezone.
   *
   * @example
   * formatRelativeTime(createdAt, { timeZone: 'America/New_York' })
   */
  readonly timeZone?: string;
  /**
   * Override labels for the `compact` style to localise ultra-dense phrases.
   * Each value is a template string with a `{n}` placeholder for the numeric value.
   * Omitted fields fall back to English defaults.
   *
   * @example
   * compactLabels: { minutesAgo: '{n} Min.', hoursAgo: '{n} Std.' }
   */
  readonly compactLabels?: PixelRelativeTimeCompactLabels;
}

const MS_PER_SECOND = 1000;
const MS_PER_MINUTE = 60 * MS_PER_SECOND;
const MS_PER_HOUR = 60 * MS_PER_MINUTE;
const MS_PER_DAY = 24 * MS_PER_HOUR;
const MS_PER_WEEK = 7 * MS_PER_DAY;
const MS_PER_MONTH = 30 * MS_PER_DAY;
const MS_PER_YEAR = 365 * MS_PER_DAY;

/**
 * Formats a past (or future) instant as a relative phrase, falling back to an absolute
 * timestamp after {@link PixelRelativeTimeOptions.absoluteAfterDays}.
 */
export function formatRelativeTime(
  value: number | string | Date,
  options: PixelRelativeTimeOptions = {},
): string {
  const timestamp = toEpochMs(value);
  if (timestamp === null) {
    return '';
  }

  const now = toEpochMs(options.now ?? Date.now()) ?? Date.now();
  const absoluteAfterDays =
    options.absoluteAfterDays === undefined ? 7 : options.absoluteAfterDays;
  const diffMs = timestamp - now;
  const absMs = Math.abs(diffMs);

  if (absoluteAfterDays !== null && absMs >= absoluteAfterDays * MS_PER_DAY) {
    return formatAbsoluteTimestamp(timestamp, options.locale, options.timeZone);
  }

  const style = options.style ?? 'long';
  if (style === 'compact') {
    return formatCompactRelativeTime(diffMs, absMs, options.locale, options.compactLabels);
  }

  const rtf = new Intl.RelativeTimeFormat(options.locale, {
    numeric: options.numeric ?? 'auto',
    style,
  });

  // First minute collapses to "now" (or locale equivalent) for notification scanability.
  if (absMs < MS_PER_MINUTE) {
    return rtf.format(0, 'second');
  }
  if (absMs < MS_PER_HOUR) {
    return rtf.format(Math.round(diffMs / MS_PER_MINUTE), 'minute');
  }
  if (absMs < MS_PER_DAY) {
    return rtf.format(Math.round(diffMs / MS_PER_HOUR), 'hour');
  }
  if (absoluteAfterDays === null) {
    if (absMs < MS_PER_WEEK) {
      return rtf.format(Math.round(diffMs / MS_PER_DAY), 'day');
    }
    if (absMs < MS_PER_MONTH) {
      return rtf.format(Math.round(diffMs / MS_PER_WEEK), 'week');
    }
    if (absMs < MS_PER_YEAR) {
      return rtf.format(Math.round(diffMs / MS_PER_MONTH), 'month');
    }
    return rtf.format(Math.round(diffMs / MS_PER_YEAR), 'year');
  }

  return rtf.format(Math.round(diffMs / MS_PER_DAY), 'day');
}

/**
 * Locale-aware absolute date + time for tooltips and absolute display mode.
 *
 * @param value  An epoch-ms number, ISO string, or `Date`.
 * @param locale BCP 47 locale; defaults to the runtime locale.
 * @param timeZone IANA timezone (e.g. `'America/New_York'`). Defaults to the viewer's
 *   browser timezone. Override when showing timestamps in a business timezone that differs
 *   from the viewer's local zone (e.g. an operator in India viewing appointments for New York).
 */
export function formatAbsoluteTimestamp(
  value: number | string | Date,
  locale?: string,
  timeZone?: string,
): string {
  const timestamp = toEpochMs(value);
  if (timestamp === null) {
    return '';
  }
  return new Date(timestamp).toLocaleString(locale, {
    dateStyle: 'medium',
    timeStyle: 'short',
    ...(timeZone ? { timeZone } : {}),
  });
}

/**
 * Compact relative formatter. When `locale` is given, attempts to produce locale-aware
 * output via `Intl.RelativeTimeFormat` with `style:'narrow'` — which gives similar density
 * (e.g. `"3 Min."` in de, `"3分"` in ja). Falls back to custom `compactLabels` overrides,
 * then to English defaults.
 */
function formatCompactRelativeTime(
  diffMs: number,
  absMs: number,
  locale?: string,
  overrides?: PixelRelativeTimeCompactLabels,
): string {
  // Attempt Intl narrow for non-default locales so we get locale-appropriate text.
  if (locale) {
    try {
      const rtf = new Intl.RelativeTimeFormat(locale, { numeric: 'always', style: 'narrow' });
      if (absMs < MS_PER_MINUTE) {
        return new Intl.RelativeTimeFormat(locale, { numeric: 'auto', style: 'narrow' }).format(
          0,
          'second',
        );
      }
      if (absMs < MS_PER_HOUR) {
        return rtf.format(Math.round(diffMs / MS_PER_MINUTE), 'minute');
      }
      if (absMs < MS_PER_DAY) {
        return rtf.format(Math.round(diffMs / MS_PER_HOUR), 'hour');
      }
      return rtf.format(Math.round(diffMs / MS_PER_DAY), 'day');
    } catch {
      // Fall through to template-label path.
    }
  }

  // Template-label path: use caller overrides or English defaults.
  const past = diffMs <= 0;
  const applyTemplate = (template: string, n: number) => template.replace('{n}', String(n));

  if (absMs < MS_PER_MINUTE) {
    return overrides?.nowLabel ?? 'now';
  }
  if (absMs < MS_PER_HOUR) {
    const n = Math.max(1, Math.round(absMs / MS_PER_MINUTE));
    return past
      ? applyTemplate(overrides?.minutesAgo ?? '{n}m ago', n)
      : applyTemplate(overrides?.minutesIn ?? 'in {n}m', n);
  }
  if (absMs < MS_PER_DAY) {
    const n = Math.max(1, Math.round(absMs / MS_PER_HOUR));
    return past
      ? applyTemplate(overrides?.hoursAgo ?? '{n}h ago', n)
      : applyTemplate(overrides?.hoursIn ?? 'in {n}h', n);
  }
  const n = Math.max(1, Math.round(absMs / MS_PER_DAY));
  return past
    ? applyTemplate(overrides?.daysAgo ?? '{n}d ago', n)
    : applyTemplate(overrides?.daysIn ?? 'in {n}d', n);
}

function toEpochMs(value: number | string | Date | undefined): number | null {
  if (value === undefined) {
    return null;
  }
  const timestamp = value instanceof Date ? value.getTime() : new Date(value).getTime();
  return Number.isFinite(timestamp) ? timestamp : null;
}
